package startup

import (
	"github.com/XWS-BSEP-Tim-13/Dislinkt_UserService/domain"
	"github.com/XWS-BSEP-Tim-13/Dislinkt_UserService/domain/enum"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"time"
)

var users = []*domain.RegisteredUser{
	{
		Id:            getObjectId("723b0cc3a34d25d8567f9f82"),
		FirstName:     "Srdjan",
		LastName:      "Sukovic",
		Email:         "srdjansukovic@gmail.com",
		PhoneNumber:   "0649459562",
		Gender:        0,
		DateOfBirth:   time.Time{},
		Biography:     "Entrepreneur, investor, and business magnate. Next I’m buying Coca-Cola to put the cocaine back in.",
		IsPrivate:     false,
		IsActive:      true,
		Username:      "srdjansukovic",
		Notifications: false,
		Experiences: []domain.Experience{
			{
				Id:                 getObjectId("723b0cc3a34d25d8567f9d72"),
				Description:        "Senior web engineer in charge of automotive project",
				StartDate:          time.Time{},
				EndDate:            time.Time{},
				Industry:           "Software",
				IsCurrentlyWorking: false,
				Location:           "Los Angeles",
				CompanyName:        "Google",
				EmploymentType:     0,
				Title:              "Full stack engineer",
			},
			{
				Id:                 getObjectId("723b0cc3a34d25d8567f9d77"),
				Description:        "Junior web engineer in charge of automotive project",
				StartDate:          time.Time{},
				EndDate:            time.Time{},
				Industry:           "Software",
				IsCurrentlyWorking: false,
				Location:           "Las Vegas",
				CompanyName:        "Facebook",
				EmploymentType:     0,
				Title:              "Full stack engineer",
			},
		},
		Educations: []domain.Education{
			{
				Id:           getObjectId("723b0cc3a34d25d8567f9d74"),
				StartDate:    time.Time{},
				EndDate:      time.Time{},
				Description:  "Graduated first in class",
				FieldOfStudy: "Computer science",
				School:       "Harvard",
				Degree:       1,
			},
		},
		Skills:       []string{"Java", "Docker"},
		BlockedUsers: []string{},
		Interests:    []primitive.ObjectID{getObjectId("623b0cc3a34d25d8567f9f82")},
		Connections:  []string{"anagavrilovic", "stefanljubovic"},
	},
	{
		Id:            getObjectId("723b0cc3a34d25d8567f9f83"),
		FirstName:     "Stefan",
		LastName:      "Ljubovic",
		Email:         "ljubovicstefan@gmail.com",
		PhoneNumber:   "0654324995",
		Username:      "stefanljubovic",
		Gender:        0,
		DateOfBirth:   time.Time{},
		Biography:     "biography sample",
		IsPrivate:     true,
		IsActive:      true,
		Notifications: true,
		Experiences: []domain.Experience{
			{
				Id:                 getObjectId("723b0cc3a34d25d8567f9d73"),
				Description:        "Junior web engineer in charge of automotive project",
				StartDate:          time.Time{},
				EndDate:            time.Time{},
				Industry:           "Software",
				IsCurrentlyWorking: false,
				Location:           "Novi Sad",
				CompanyName:        "Synechron",
				EmploymentType:     0,
				Title:              "Full stack engineer",
			},
			{
				Id:                 getObjectId("723b0cc3a34d25d8567f9d79"),
				Description:        "Junior web engineer in charge of automotive project",
				StartDate:          time.Time{},
				EndDate:            time.Time{},
				Industry:           "Software",
				IsCurrentlyWorking: false,
				Location:           "Novi Sad",
				CompanyName:        "Symphony",
				EmploymentType:     0,
				Title:              "DevOps engineer",
			},
		},
		Educations:   []domain.Education{},
		Skills:       []string{"AWS", "Java"},
		Interests:    []primitive.ObjectID{},
		BlockedUsers: []string{"marijakljestan"},
		Connections:  []string{"srdjansukovic"},
	},
	{
		Id:            getObjectId("723b0cc3a34d25d8567f9f84"),
		FirstName:     "Ana",
		LastName:      "Gavrilovic",
		Email:         "anagavrilovic@gmail.com",
		PhoneNumber:   "0642152",
		Username:      "anagavrilovic",
		Gender:        1,
		DateOfBirth:   time.Time{},
		Biography:     "biography sample",
		IsPrivate:     false,
		Notifications: true,
		Experiences: []domain.Experience{
			{
				Id:                 getObjectId("723b0cc3a34d25d8567f9d74"),
				Description:        "Junior web engineer in charge of automotive project",
				StartDate:          time.Time{},
				EndDate:            time.Time{},
				Industry:           "Software",
				IsCurrentlyWorking: false,
				Location:           "Novi Sad",
				CompanyName:        "Synechron",
				EmploymentType:     0,
				Title:              "Full stack engineer",
			},
			{
				Id:                 getObjectId("723b0cc3a34d25d8567f9d78"),
				Description:        "Junior web engineer in charge of automotive project",
				StartDate:          time.Time{},
				EndDate:            time.Time{},
				Industry:           "Software",
				IsCurrentlyWorking: false,
				Location:           "Novi Sad",
				CompanyName:        "Smart Cat",
				EmploymentType:     0,
				Title:              "DevOps engineer",
			},
		},
		Educations:   []domain.Education{},
		Skills:       []string{"Java", "Docker"},
		BlockedUsers: []string{},
		Interests:    []primitive.ObjectID{},
		Connections:  []string{"srdjansukovic,lenka"},
	},
	{
		Id:            getObjectId("723b0cc3a34d25d8567f9f85"),
		FirstName:     "Marija",
		LastName:      "Kljestan",
		Email:         "marijakljestan@gmail.com",
		PhoneNumber:   "0642152643",
		Username:      "marijakljestan",
		Gender:        1,
		DateOfBirth:   time.Time{},
		Biography:     "biography sample",
		IsPrivate:     false,
		IsActive:      true,
		Notifications: false,
		Experiences: []domain.Experience{
			{
				Id:                 getObjectId("723b0cc3a34d25d8567f9d75"),
				Description:        "Junior web engineer in charge of automotive project",
				StartDate:          time.Time{},
				EndDate:            time.Time{},
				Industry:           "Software",
				IsCurrentlyWorking: false,
				Location:           "Novi Sad",
				CompanyName:        "Levi9",
				EmploymentType:     0,
				Title:              "Java engineer",
			},
			{
				Id:                 getObjectId("723b0cc3a34d25d8567f9d76"),
				Description:        "Junior web engineer in charge of automotive project",
				StartDate:          time.Time{},
				EndDate:            time.Time{},
				Industry:           "Software",
				IsCurrentlyWorking: false,
				Location:           "Novi Sad",
				CompanyName:        "Symphony",
				EmploymentType:     0,
				Title:              "DevOps engineer",
			},
		},
		Educations:   []domain.Education{},
		BlockedUsers: []string{"stefanljubovic"},
		Skills:       []string{"AWS", "Docker"},
		Interests:    []primitive.ObjectID{},
		Connections:  []string{"lenka"},
	},
	{
		Id:            getObjectId("723b0cc3a34d25d8567f9f86"),
		FirstName:     "Lenka",
		LastName:      "Aleksic",
		Email:         "lenka@gmail.com",
		PhoneNumber:   "064364364",
		Username:      "lenka",
		Gender:        1,
		DateOfBirth:   time.Time{},
		Biography:     "biography sample",
		IsPrivate:     false,
		IsActive:      true,
		Experiences:   []domain.Experience{},
		Educations:    []domain.Education{},
		Skills:        []string{"Java", "C#"},
		BlockedUsers:  []string{},
		Interests:     []primitive.ObjectID{},
		Connections:   []string{},
		Notifications: false,
	},
	{
		Id:            getObjectId("723b0cc3a34d25d8567f9f87"),
		FirstName:     "Admin",
		LastName:      "",
		Email:         "admin@gmail.com",
		PhoneNumber:   "064364374",
		Username:      "admin",
		Gender:        0,
		DateOfBirth:   time.Time{},
		Biography:     "Dislinkt admin",
		IsPrivate:     false,
		IsActive:      true,
		Experiences:   []domain.Experience{},
		Educations:    []domain.Education{},
		Skills:        []string{"Java", "C#"},
		BlockedUsers:  []string{},
		Interests:     []primitive.ObjectID{},
		Connections:   []string{},
		Notifications: false,
	},
}

var connections []*domain.ConnectionRequest

var notifications = []*domain.Notification{
	{
		Id:               getObjectId("723b0cc3a34d25d8567f9f82"),
		Username:         "srdjansukovic",
		NotificationType: enum.NotificationType(0),
		Created:          time.Now(),
	},
	{
		Id:               getObjectId("723b0cc3a34d25d8567f9f83"),
		Username:         "srdjansukovic",
		NotificationType: enum.NotificationType(1),
		Created:          time.Now(),
	},
	{
		Id:               getObjectId("723b0cc3a34d25d8567f9f84"),
		Username:         "srdjansukovic",
		NotificationType: enum.NotificationType(0),
		Created:          time.Now(),
	},
}

func getObjectId(id string) primitive.ObjectID {
	if objectId, err := primitive.ObjectIDFromHex(id); err == nil {
		return objectId
	}
	return primitive.NewObjectID()
}
